# Generated by Django 2.1.5 on 2019-03-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='interests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_mentee', to='mentee.Subject'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='interests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_mentor', to='mentee.Subject'),
        ),
    ]
