# Generated by Django 2.1.5 on 2019-05-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='interests',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='mentee.Subject'),
        ),
    ]
