# Generated by Django 2.1.5 on 2019-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_auto_20190304_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='reply',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
