# Generated by Django 2.1.5 on 2019-03-16 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0004_auto_20190316_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='replied_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
