# Generated by Django 2.1.5 on 2019-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0005_msg_replied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='interests',
            field=models.ManyToManyField(related_name='mentees', to='mentee.Subject'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='interests',
            field=models.ManyToManyField(related_name='mentors', to='mentee.Subject'),
        ),
    ]
