# Generated by Django 2.1.5 on 2019-03-18 20:22

from django.db import migrations, models
import mentee.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0007_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(verbose_name=mentee.models.Msg),
        ),
    ]
