# Generated by Django 2.1.5 on 2019-03-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0008_auto_20190318_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
