# Generated by Django 2.1.5 on 2019-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0009_auto_20190318_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approve?'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
