# Generated by Django 2.1.5 on 2019-03-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0010_auto_20190322_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='reply',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='replied_at',
            new_name='comment_at',
        ),
    ]
