# Generated by Django 2.1.5 on 2019-03-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0011_auto_20190322_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='author',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
