# Generated by Django 2.1.5 on 2019-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0012_auto_20190322_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveField(
            model_name='msg',
            name='created_at',
        ),
        migrations.AddField(
            model_name='msg',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msg',
            name='sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
