# Generated by Django 2.1.5 on 2019-03-24 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0013_auto_20190324_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='comment_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='msg',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
