# Generated by Django 2.1.5 on 2019-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0014_auto_20190324_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='comment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
