# Generated by Django 2.1.5 on 2019-03-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0016_remove_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='interests',
        ),
        migrations.AddField(
            model_name='mentee',
            name='interests',
            field=models.CharField(choices=[('Network Programming', 'Network Programming'), ('Business', 'Business')], default=[('Network Programming', 'Network Programming'), ('Business', 'Business')], max_length=1),
        ),
    ]
