# Generated by Django 2.1.5 on 2019-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0017_auto_20190329_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='interests',
            field=models.CharField(choices=[('Network Programming', 'Network Programming'), ('Business', 'Business')], default='Business', max_length=1),
        ),
    ]
