# Generated by Django 2.1.5 on 2019-03-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0019_auto_20190329_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='interests',
        ),
        migrations.AddField(
            model_name='mentee',
            name='interests',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='mentee.Subject'),
        ),
    ]
