# Generated by Django 2.1.5 on 2019-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0020_auto_20190329_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='interests',
        ),
        migrations.AddField(
            model_name='mentee',
            name='interests',
            field=models.ManyToManyField(related_name='mentees', to='mentee.Subject'),
        ),
    ]
