# Generated by Django 2.1.5 on 2019-04-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0021_auto_20190329_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.TextField(max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('receipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipient1', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
