# Generated by Django 2.1.5 on 2019-04-30 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0022_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mentee.Conversation'),
        ),
        migrations.AddField(
            model_name='reply',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender2', to=settings.AUTH_USER_MODEL),
        ),
    ]
