# Generated by Django 2.1.5 on 2019-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0025_auto_20190503_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.CharField(default='BBIT/2014/62324', max_length=100),
        ),
    ]
